# FANTOM Configuration
# AI-driven 3D printing slicer with FOSS components
# ⚠️ Modify settings at your own risk

# Application Settings
app:
  name: "FANTOM"
  version: "0.1.0"
  theme: "Material"
  font_family: "Play"
  developer_mode: false  # ⚠️ Enables experimental AI features
  show_disclaimers: true  # Required for liability protection

# Ghost AI Configuration  
ghosts:
  enabled: true  # ⚠️ Enables AI collaboration features
  max_concurrent: 4
  internet_access: true  # Required for FOSS research
  auto_pr: false  # Require manual approval for PRs
  
  # Ghost Types and Capabilities
  analysis:
    enabled: true
    optimization_level: "conservative"  # conservative|aggressive|experimental
  
  optimization:
    enabled: true
    max_iterations: 5
    
  error_handling:
    enabled: true
    auto_analyze: true
    submit_fixes: false  # Require manual review
    
  research:
    enabled: true
    foss_only: true  # Only use FOSS libraries and tools

# Printer Profiles (Examples)
printers:
  default:
    name: "Generic FDM"
    bed_size: [200, 200, 200]  # X, Y, Z in mm
    nozzle_diameter: 0.4
    max_temp_hotend: 260
    max_temp_bed: 80
    
  prusa_mk3s:
    name: "Prusa MK3S+"
    bed_size: [250, 210, 210]
    nozzle_diameter: 0.4
    max_temp_hotend: 300
    max_temp_bed: 120

# Material Profiles (FOSS database)
materials:
  pla:
    name: "PLA"
    temp_hotend: 210
    temp_bed: 60
    density: 1.24  # g/cm³
    
  petg:
    name: "PETG"  
    temp_hotend: 240
    temp_bed: 80
    density: 1.27

# Slicing Parameters
slicing:
  layer_height: 0.2
  infill_density: 0.15  # 15%
  print_speed: 50  # mm/s
  travel_speed: 120  # mm/s
  
  # Advanced settings (⚠️ Experimental)
  adaptive_layers: false
  ai_optimization: false  # Requires developer mode
  ghost_suggestions: false  # AI-driven improvements

# Safety and Legal
safety:
  show_startup_disclaimer: true
  require_ack_developer_mode: true
  log_ghost_actions: true
  backup_before_changes: true
  
  # Liability protection
  no_warranty: true
  user_assumes_risk: true
  
# Logging
logging:
  level: "INFO"  # DEBUG|INFO|WARNING|ERROR
  file: "slicergpt.log"
  max_size_mb: 50
  backup_count: 3
  
# Development (for contributors)
development:
  debug_mode: false
  verbose_ghost_logs: false
  test_mode: false
  
# ⚠️ IMPORTANT DISCLAIMERS:
# - All settings used at your own risk
# - SlicerGPT assumes no liability for print failures or damage
# - AI features are experimental and may produce unpredictable results  
# - Always verify generated G-code before printing
# - Developer mode enables potentially dangerous experimental features
# - Ghost AI actions are logged but not guaranteed safe
# - User is responsible for all configuration choices and outcomes
