name: GHST Dependency Management & Vulnerability Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-tools and pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools pip-audit safety
      - name: Compile requirements
        run: |
          pip-compile requirements.in || pip-compile requirements.txt
      - name: Audit dependencies for vulnerabilities
        run: |
          pip-audit -r requirements.txt
          safety check -r requirements.txt
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: ghst-dependency-audit
          path: .
